package test_package;

public class Exception_Handling_Class1 {
	public static void main(String[] args) {
		
		int i;
		System.out.println("Program Starts");
		try{
			System.out.println("try block1 starts");
			i=10/10;
			System.out.println("i= "+i);
			System.out.println("try Block Executes");
		try{
			System.out.println("try block2 starts");
			i=10/0;
			System.out.println("i= "+i);
			System.out.println("try Block Executes");
		}
		finally{
			System.out.println("Finally block2 starts");
			
		}
		}
		catch(ArithmeticException exp){
			System.out.println("Airthmetic Exception block starts");
			System.out.println(exp);
			
			}
		catch (NumberFormatException exp) {
			System.out.println("NumberFormatException block starts");
			
		}
		catch (NullPointerException exp) {
			System.out.println("NullPointerException block starts");
			
		}
		catch (Exception e) {
			System.out.println("Exception block starts");
			
		}
		
		finally{
			System.out.println("Finally block1 starts");
			
		}
		
	
		
		System.out.println("Program Ends");
		
		
	}}


//If No Error in try block , try block Executes and Finally block Executes
	
